== Quarkus cli Example

This project uses Quarkus, the Supersonic Subatomic Java Framework.

If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

It uses following extentions:

* https://quarkus.io/guides/picocli[picocli]
* https://quarkus.io/guides/rest-client[rest-client]

=== Goal

The project is testing how a REST-Client to retrieve data from a sonar server can be implemented.

=== Configure Sonar Server

Add the necessary config to connect to your SonarQube server to sonarcloud.io

[source,bash]
----
export SONAR_API_TOKEN=dda9cccaf7d6fae17708ea7af3eccc9f9c714313
export SONAR_URL=https://sonar.example.com/
----

=== Running the application in dev mode

You can run your application in dev mode that enables live coding using:

You need to provide a project key (`a_project` in this example) and a pull request id (`31` in this example):

[source,bash]
----
./gradlew quarkusDev --quarkus-args='TEST --projectKey=a_project --pullRequest=31'
----

> **_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

=== Packaging and running the application

The application can be packaged using:

[source,bash]
----
./gradlew build
----

It produces the `quarkus-run.jar` file in the `build/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `build/quarkus-app/lib/` directory.

The application is now runnable using `java -jar build/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:

[source,bash]
----
./gradlew build -Dquarkus.package.type=uber-jar
----

The application, packaged as an _über-jar_, is now runnable using `java -jar build/*-runner.jar`.

=== Creating a native executable

You can create a native executable using: 

[source,bash]
----
./gradlew build -Dquarkus.package.type=native
----

Or, if you don't have GraalVM installed, you can run the native executable build in a container using: 

[source,bash]
----
./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
----

You can then execute your native executable with: `./build/cli-1.0.0-SNAPSHOT-runner`

If you want to learn more about building native executables, please consult https://quarkus.io/guides/gradle-tooling.

=== Related Guides

* REST Client Classic (https://quarkus.io/guides/rest-client[guide]): Call REST services
* Picocli (https://quarkus.io/guides/picocli[guide]): Develop command line applications with Picocli
