== Multimodule quarkus app experiment

This project uses Quarkus.
If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

Test of a multi-module gradle project

=== Setup

This folder contains 2 quarkus app:

* `:app1`
* `:app2`

that use both the same core library: `:core-lib`

=== Running the application in dev mode

You can run your application in dev mode that enables live coding using:

> **_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at http://localhost:8080/q/dev/.

==== App 1

```shell script
./gradlew app1:quarkusDev
```

==== App 2

```shell script
./gradlew app2:quarkusDev
```

=== Packaging and running the application

The application can be packaged using:
```shell script
./gradlew build
```
It produces the `quarkus-run.jar` file in the `build/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `build/quarkus-app/lib/` directory.

The application is now runnable using `java -jar build/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:
```shell script
./gradlew build -Dquarkus.package.type=uber-jar
```

The application, packaged as an _über-jar_, is now runnable using `java -jar build/*-runner.jar`.

==== App 1

```shell script
java -jar app1/build/quarkus-app/quarkus-run.jar
```

==== App 2

```shell script
java -jar app2/build/quarkus-app/quarkus-run.jar
```

=== Notes on the experiment

See the xref:NOTES.adoc[NOTES] document.
